[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python -m uvicorn app:app --host 0.0.0.0 --port $PORT" 