[build]
builder = "nixpacks"

[nixpacks]
python_version = "3.10"

[nixpacks.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[deploy]
startCommand = "python3 -m uvicorn app:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
healthcheckInterval = 15
